In [2]:
import numpy as np

In [ ]:
array_2d = np.array([[(i, j) for j in range(2000)] for i in range(20000)])
# Simpler way using np.indices
array_2d = np.indices((4, 5)).transpose(1, 2, 0)
print(array_2d)

[[[0 0]
  [0 1]
  [0 2]
  [0 3]
  [0 4]]

 [[1 0]
  [1 1]
  [1 2]
  [1 3]
  [1 4]]

 [[2 0]
  [2 1]
  [2 2]
  [2 3]
  [2 4]]

 [[3 0]
  [3 1]
  [3 2]
  [3 3]
  [3 4]]]


In [3]:
indices = np.indices((5,4))
#array_2d = np.array([[(i, j) for j in range(2000)] for i in range(20000)])
indices


array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [92]:
u,v = 115,107 # center
r = 50 # radius

In [93]:
indices_y1,indices_x1 = indices
distances = (indices_x1 - u)**2 + (indices_y1 - v)**2 # CP^2
indices_x2 = u + r**2/distances * (indices_x1 - u)

indices_y2 = v + r**2/distances * (indices_y1 - v)

C:\Users\rrrad\AppData\Local\Temp\ipykernel_9008\1013446361.py:3: RuntimeWarning: divide by zero encountered in divide
  indices_x2 = u + r**2/distances * (indices_x1 - u)
C:\Users\rrrad\AppData\Local\Temp\ipykernel_9008\1013446361.py:3: RuntimeWarning: invalid value encountered in multiply
  indices_x2 = u + r**2/distances * (indices_x1 - u)
C:\Users\rrrad\AppData\Local\Temp\ipykernel_9008\1013446361.py:5: RuntimeWarning: divide by zero encountered in divide
  indices_y2 = v + r**2/distances * (indices_y1 - v)
C:\Users\rrrad\AppData\Local\Temp\ipykernel_9008\1013446361.py:5: RuntimeWarning: invalid value encountered in multiply
  indices_y2 = v + r**2/distances * (indices_y1 - v)


In [ ]:
indices_y2

C:\Users\rrrad\AppData\Local\Temp\ipykernel_9008\4172567625.py:1: RuntimeWarning: divide by zero encountered in divide
  indices_x2 = u + r**2/distances * (indices_x1 - u)
C:\Users\rrrad\AppData\Local\Temp\ipykernel_9008\4172567625.py:1: RuntimeWarning: invalid value encountered in multiply
  indices_x2 = u + r**2/distances * (indices_x1 - u)


In [49]:
indices_x1[51,50]-u

np.int64(1)

In [78]:
indices_x2

array([[49.        , 49.00020404, 49.00083264, ..., 50.99808877,
        50.99916736, 50.99979596],
       [48.97980004, 48.97959184, 48.97980871, ..., 51.01952278,
        51.02019129, 51.02040816],
       [48.95920067, 48.95855473, 48.95833333, ..., 51.04143585,
        51.04166667, 51.04144527],
       ...,
       [48.93820344, 48.93709328, 48.93640594, ..., 51.06382979,
        51.06359406, 51.06290672],
       [48.95920067, 48.95855473, 48.95833333, ..., 51.04143585,
        51.04166667, 51.04144527],
       [48.97980004, 48.97959184, 48.97980871, ..., 51.01952278,
        51.02019129, 51.02040816]], shape=(100, 100))

In [68]:
distances[0,0]

np.int64(50)

In [25]:
indices_y1[0]

array([   0,    1,    2, ..., 1997, 1998, 1999], shape=(2000,))

In [94]:
from PIL import Image
import numpy as np

# Load image and convert to numpy array
image = Image.open('image.png')
image_array = np.array(image)
print(image_array.shape) # reversed shape

(235, 214, 3)


In [82]:
from scipy.ndimage import map_coordinates

# Prepare coordinates for mapping
coords = np.vstack([indices_y2.ravel(), indices_x2.ravel()])

# Apply mapping for each channel
warped = np.zeros((100, 100, image_array.shape[2]), dtype=image_array.dtype)
for c in range(image_array.shape[2]):
    warped[..., c] = map_coordinates(image_array[..., c], coords, order=1, mode='reflect').reshape(100, 100)

warped

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [100]:
from numba import vectorize
@vectorize
def myfunc(indice_x,indice_y):
    return image_array[indice_y,indice_x,0]

myfunc(indices_x2, indices_y2)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(readonly array(uint8, 3d, C), Tuple(float64, float64, Literal[int](0)))
 
There are 22 candidate implementations:
    - Of which 20 did not match due to:
    Overload of function 'getitem': File: <numerous>: Line N/A.
      With argument(s): '(readonly array(uint8, 3d, C), Tuple(float64, float64, int64))':
     No match.
    - Of which 1 did not match due to:
    Overload in function 'GetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 211.
      With argument(s): '(readonly array(uint8, 3d, C), Tuple(float64, float64, int64))':
     Rejected as the implementation raised a specific error:
       NumbaTypeError: Unsupported array index type float64 in Tuple(float64, float64, int64)
  raised from C:\Users\rrrad\AppData\Roaming\Python\Python313\site-packages\numba\core\typing\arraydecl.py:104
    - Of which 1 did not match due to:
    Overload in function 'GetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 211.
      With argument(s): '(readonly array(uint8, 3d, C), Tuple(float64, float64, Literal[int](0)))':
     Rejected as the implementation raised a specific error:
       NumbaTypeError: Unsupported array index type float64 in Tuple(float64, float64, Literal[int](0))
  raised from C:\Users\rrrad\AppData\Roaming\Python\Python313\site-packages\numba\core\typing\arraydecl.py:104

During: typing of intrinsic-call at C:\Users\rrrad\AppData\Local\Temp\ipykernel_9008\2324517020.py (4)

File "..\..\..\..\AppData\Local\Temp\ipykernel_9008\2324517020.py", line 4:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [104]:
i=np.round(indices_x2)[0,0]

In [106]:
indices_x2.astype(np.int64)

C:\Users\rrrad\AppData\Local\Temp\ipykernel_9008\4152098255.py:1: RuntimeWarning: invalid value encountered in cast
  indices_x2.astype(np.int64)


array([[103, 103, 103, ..., 126, 126, 126],
       [103, 103, 103, ..., 126, 126, 126],
       [103, 103, 103, ..., 126, 126, 126],
       ...,
       [105, 105, 105, ..., 124, 124, 124],
       [105, 105, 105, ..., 124, 124, 124],
       [105, 105, 105, ..., 124, 124, 124]], shape=(235, 214))

In [96]:
image_array

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [88]:
a=np.random.rand(100,100)
b=np.random.rand(100,100)

In [89]:
a+b

array([[1.70300759, 0.76711252, 1.4322551 , ..., 0.42597527, 1.03889635,
        0.6085949 ],
       [1.23492519, 1.52002416, 1.1464232 , ..., 0.4363074 , 1.09967078,
        1.40151733],
       [0.80356434, 0.72543347, 0.21741598, ..., 0.42662757, 0.82031372,
        0.73749846],
       ...,
       [1.14572835, 1.61668058, 1.42088963, ..., 1.33323899, 0.94569728,
        1.21896761],
       [1.51998608, 1.36403436, 0.9988623 , ..., 1.5582967 , 1.16109778,
        0.87743215],
       [1.70063229, 0.86909803, 0.33573767, ..., 0.79563073, 0.77228501,
        1.01728529]], shape=(100, 100))

In [90]:
myfunc(a,b)

array([[1.70300759, 0.76711252, 1.4322551 , ..., 0.42597527, 1.03889635,
        0.6085949 ],
       [1.23492519, 1.52002416, 1.1464232 , ..., 0.4363074 , 1.09967078,
        1.40151733],
       [0.80356434, 0.72543347, 0.21741598, ..., 0.42662757, 0.82031372,
        0.73749846],
       ...,
       [1.14572835, 1.61668058, 1.42088963, ..., 1.33323899, 0.94569728,
        1.21896761],
       [1.51998608, 1.36403436, 0.9988623 , ..., 1.5582967 , 1.16109778,
        0.87743215],
       [1.70063229, 0.86909803, 0.33573767, ..., 0.79563073, 0.77228501,
        1.01728529]], shape=(100, 100))